### ISSUE TITLE
PaperLaunch overlay blocks side gestures for underlaying (main) apps

### ISSUE THREAD

**Issue by melohr** [devmil/PaperLaunch#1]
I really love this app, but there's one annoying behaviour (in parts inherent to the way it works). As PaperLaunch reacts on slide gestures from the screen edges, it prevents the main (foreground) app from getting this event. Hence, it's not possible any more to use this gesture. This could be seen as "convenience" issue, since - from left screen edge - normally, there's the "3 bars" menu. However, I also have apps where I have a right side drag menu without another way to access it. So these will be completely useless. For me, this changes "convenience" to "showstopper". This behaviour does not change even when restricting PaperLauch's sensibility and screen area to e.g. lower edges.

Would it be possible to change the size of the "screen side area" (event area) in accordance with the area PaperLaunch actually shows the launcher and otherwise passes the event to the foreground app?

**Comment by Spleeeno** [comment]
Paperlaunch -> Hamburger Menu -> Settings -> Height/Position
I have its set on the middle 50% of the screen, swipes blow or above that dont trigger PaperLaunch for me.

**Comment by melohr** [comment]
Thank you for the hint. However, I already tried to customize the "activate" area and reduced sensitivity to the absolute minimum (slider at max. left position). The apps I acutally have problems with are Llama (lock profile buttons, which are _really_ small) and Business Calendar 2 (no real possibility to use "select appointment time" by right side slide gesture to open a kind of "day view"). As I am right-handed, switching it to the left side is no choice for me.
Perhaps, an even smaller area at the side (sensitivity setting) could help reduce the issue...

**Comment by devmil** [comment]
@melohr you are right. The container holding the activation area gets these touch events and they aren't delivered to the underlying window.
I will change the way this mechanics work so that only touch events that hit the activation area are consumed

**Comment by devmil** [comment]
I released a beta version to the play store that should fix this issue.
Can you check it out?
Activation link:
https://play.google.com/apps/testing/de.devmil.paperlaunch

**Comment by melohr** [comment]
Perfect! The beta solves the problem entirely! Thanks a lot!
